In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from dlclive import DLCLive, Processor
import dlclive
from dlclive.display import Display
import cv2
import numpy as np 

Loading DLC 3.0.0rc4...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)


/media1/data/dikra/miniconda/envs/dlc-live/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
dlc_proc = Processor()
#Dikra
dlc_live = DLCLive(pytorch_cfg="/media1/data/dikra/fly-kevin", processor=dlc_proc, snapshot='/media1/data/dikra/fly-kevin/snapshot-100.pt', model_type='onnx')
img = cv2.imread("/media1/data/dikra/fly-kevin/img001.png")
img = img / 255.0
img = np.array(img, dtype=np.float32)
img = img.reshape(1, 3, 540, 682)

# Anna
# dlc_live = DLCLive(pytorch_cfg="/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/train", processor=dlc_proc, snapshot='/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/train/snapshot-263.pt')
# dlc_live = DLCLive("/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/exported DLC model for dlc-live/DLC_dev-single-animal_resnet_50_iteration-1_shuffle-1", processor=dlc_proc)
# img = cv2.imread("/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/exported DLC model for dlc-live/img049.png")

pose = dlc_live.init_inference(frame=img)
pose

/media1/data/dikra/DLC_AI2024/DeepLabCut-live/dlclive/utils.py:102: DLCLiveWarning: Image has 4 dimensions. Must be 2 or 3 dimensions to convert to RGB
  warnings.warn(


16.0
torch.Size([1, 25, 69, 87])
torch.Size([1, 69, 87, 25])
torch.Size([1, 50, 69, 87])
torch.Size([1, 69, 87, 25, 2])
dz torch.Size([1, 1, 25, 3])
tensor([[[10, 22, 24, 11, 18, 11, 20, 12, 13, 11, 11, 18, 13, 60, 10, 17,  5,
           5, 27, 57, 18, 19, 19, 21, 18]]]) tensor([[[54, 61, 60, 52, 20, 55, 62, 53, 53, 52, 52, 62, 53, 12, 53, 17, 38,
          38, 32, 44, 62, 60, 62, 62, 60]]])
tensor([[[164.1184, 358.2253, 392.0227, 183.4705, 295.2524, 182.2032, 322.3113,
          189.5103, 209.1273, 180.8862, 180.5940, 305.8344, 212.8524, 966.0091,
          165.3865, 282.4215,  84.4847,  85.8932, 438.0833, 920.9091, 299.0209,
          304.5890, 312.2062, 334.7838, 297.6540]]]) tensor([[[ 869.9263,  989.9418,  969.7960,  837.6666,  330.6241,  879.7804,
          1003.5058,  862.9377,  863.4908,  846.4874,  846.7697,  997.7080,
           862.4837,  200.4533,  857.4780,  291.5507,  616.6808,  616.0269,
           518.3417,  712.0759,  997.5941,  970.5095,  998.2376,  999.5897,
        

{'poses': tensor([[[[8.6993e+02, 1.6412e+02, 5.4712e-01],
           [9.8994e+02, 3.5823e+02, 5.6155e-01],
           [9.6980e+02, 3.9202e+02, 5.3089e-01],
           [8.3767e+02, 1.8347e+02, 5.3233e-01],
           [3.3062e+02, 2.9525e+02, 5.3193e-01],
           [8.7978e+02, 1.8220e+02, 5.4962e-01],
           [1.0035e+03, 3.2231e+02, 5.2076e-01],
           [8.6294e+02, 1.8951e+02, 5.4794e-01],
           [8.6349e+02, 2.0913e+02, 5.2978e-01],
           [8.4649e+02, 1.8089e+02, 5.1860e-01],
           [8.4677e+02, 1.8059e+02, 5.2254e-01],
           [9.9771e+02, 3.0583e+02, 5.4478e-01],
           [8.6248e+02, 2.1285e+02, 5.3896e-01],
           [2.0045e+02, 9.6601e+02, 5.7191e-01],
           [8.5748e+02, 1.6539e+02, 5.5855e-01],
           [2.9155e+02, 2.8242e+02, 5.4177e-01],
           [6.1668e+02, 8.4485e+01, 5.5206e-01],
           [6.1603e+02, 8.5893e+01, 5.3894e-01],
           [5.1834e+02, 4.3808e+02, 5.3493e-01],
           [7.1208e+02, 9.2091e+02, 5.4254e-01],
           

In [49]:
img = (img /255.0)
img

array([[[[0.85714286, 0.85714286, 0.85714286, ..., 0.80184332,
          0.80184332, 0.80645161],
         [0.80645161, 0.80645161, 0.80645161, ..., 0.79723502,
          0.79262673, 0.79262673],
         [0.79262673, 0.79262673, 0.79262673, ..., 0.75115207,
          0.75115207, 0.75115207],
         ...,
         [0.87096774, 0.87096774, 0.87096774, ..., 0.83870968,
          0.83870968, 0.84331797],
         [0.84331797, 0.84331797, 0.84331797, ..., 0.75115207,
          0.75115207, 0.75115207],
         [0.75115207, 0.75115207, 0.75115207, ..., 0.66820276,
          0.66820276, 0.66820276]],

        [[0.87096774, 0.87096774, 0.87096774, ..., 0.83870968,
          0.83870968, 0.84331797],
         [0.84331797, 0.84331797, 0.84331797, ..., 0.75115207,
          0.75115207, 0.75115207],
         [0.75115207, 0.75115207, 0.75115207, ..., 0.68202765,
          0.68202765, 0.68202765],
         ...,
         [0.85253456, 0.85253456, 0.85253456, ..., 0.77880184,
          0.77880184, 0.7

In [5]:
pose

{'poses': tensor([[[[5.2543e+02, 6.1445e+02, 5.1050e-01],
           [5.2196e+02, 8.7184e+02, 5.0796e-01],
           [1.5571e+02, 4.3918e+02, 5.0677e-01],
           [4.7259e+02, 8.5782e+02, 5.0612e-01],
           [5.3711e+02, 9.0339e+02, 5.0850e-01],
           [5.3878e+02, 5.7034e+02, 5.0488e-01],
           [6.0229e+02, 5.8371e+02, 5.0476e-01],
           [1.0788e+02, 4.4067e+02, 5.0910e-01],
           [5.0485e+02, 8.4273e+02, 5.0626e-01],
           [5.0645e+02, 8.8957e+02, 5.0453e-01],
           [4.5770e+02, 4.4161e+02, 5.0402e-01],
           [1.5362e+02, 4.7237e+02, 5.0679e-01],
           [4.9051e+02, 8.7022e+02, 5.0546e-01],
           [5.2387e+02, 8.8910e+02, 5.0799e-01],
           [4.4336e+02, 9.1969e+02, 5.0436e-01],
           [5.5704e+02, 5.8523e+02, 5.4445e-01],
           [4.7651e+02, 8.8554e+02, 5.1092e-01],
           [5.0078e+02, 8.8554e+02, 5.0698e-01],
           [5.0676e+02, 6.6456e+02, 5.2567e-01],
           [4.5968e+02, 8.8792e+02, 5.2051e-01],
           

In [25]:
pose = pose['bodypart']['poses'].detach().numpy()

In [26]:
pose

array([[[[1.50623795e+02, 4.26665405e+02, 1.31665707e-01],
         [7.03950043e+01, 3.00889435e+02, 2.12462395e-01],
         [1.20490944e+02, 3.39501678e+02, 3.52408379e-01],
         [1.20275337e+02, 3.35501648e+02, 5.50782263e-01],
         [1.14476669e+02, 3.29424255e+02, 7.09549904e-01],
         [1.34320312e+02, 3.17446777e+02, 4.05246109e-01],
         [8.02581100e+01, 2.13467072e+02, 6.06775761e-01],
         [5.64953079e+01, 3.07987579e+02, 2.57665426e-01],
         [1.21609062e+02, 2.50483994e+02, 7.23588467e-01],
         [1.37204422e+02, 2.28917755e+02, 7.62043774e-01],
         [1.43186707e+02, 2.11313324e+02, 7.13593900e-01],
         [1.60586777e+02, 2.75776917e+02, 5.40868521e-01],
         [1.34510666e+02, 2.64735901e+02, 2.34451458e-01],
         [1.41755417e+02, 3.78870758e+02, 8.52711260e-01],
         [1.49334778e+02, 3.65215698e+02, 7.08450615e-01],
         [2.68088665e+01, 1.99497803e+02, 7.40159988e-01],
         [2.78737526e+01, 3.44328308e+02, 8.09524894e-01

In [20]:
pose = pose.reshape((-1, 3))

In [21]:
pose.shape

(25, 3)

In [34]:
display = Display()
display.set_display(im_size=(540,682,3), bodyparts=25)
display.display_frame(img, pose)

TclError: no display name and no $DISPLAY environment variable

In [ ]:
display.destroy()

In [32]:
tmp = np.random.rand(3, 3)
tmp[0, 2]




0.7918957721065413