In [1]:
from dlclive import DLCLive, Processor
import dlclive
from dlclive.display import Display
import cv2
import numpy as np 

Loading DLC 3.0.0rc2...


/Users/annastuckert/anaconda3/envs/deeplabcut3/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [39]:
def analyze_video2(video_path: str, dlc_live):
    # Load video
    cap = cv2.VideoCapture(video_path)
    poses = []
    frame_index = 0

    ###

    while True:
        ret, frame = cap.read()
        if not ret:
            break  # End of video

        # Prepare the frame for the model
        print("a")
        frame = np.array(frame, dtype=np.float32)
        print("b")
        frame = np.transpose(frame,(2,0,1)) 
        print("c")
        frame = frame.reshape(1, frame.shape[0], frame.shape[1], frame.shape[2])
        print("e")
        frame = (frame / 255.0)
        print("f")
        #print(frame)
        
        # Analyze the frame using the get_pose function
        pose = dlc_live.get_pose(frame)
        print("g")
        
        # Store the pose for this frame
        poses.append(pose)
        print(pose["bodypart"]["poses"][0][0][0])
    

        frame_index += 1
        print(frame_index)
    
    # Release the video capture object
    cap.release()
    
    return poses

In [ ]:
# # code for trying to write a video writer of key points labelled on the video - does not work

# def analyze_video2(video_path: str, dlc_live):
#     # Load video
#     cap = cv2.VideoCapture(video_path)
#     poses = []
#     frame_index = 0

#     #ADD FOR VIDEO RECORDING
#     # Get the width, height, and frames per second of the video
#     width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
#     height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
#     fps = cap.get(cv2.CAP_PROP_FPS)
    
#     # Initialize the VideoWriter object to save the output video
#     fourcc = cv2.VideoWriter_fourcc(*'XVID')
#     out = cv2.VideoWriter("/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/test.avi", fourcc, fps, (width, height))


#     ###

#     while True:
#         ret, frame = cap.read()
#         if not ret:
#             break  # End of video

#         # Prepare the frame for the model
#         print("a")
#         frame = np.array(frame, dtype=np.float32)
#         print("b")
#         frame = np.transpose(frame,(2,0,1)) 
#         print("c")
#         frame = frame.reshape(1, frame.shape[0], frame.shape[1], frame.shape[2])
#         print("e")
#         frame = (frame / 255.0)
#         print("f")
#         #print(frame)
        
#         # Analyze the frame using the get_pose function
#         pose = dlc_live.get_pose(frame)
#         print("g")
        
#         # Store the pose for this frame
#         poses.append(pose)
#         print(pose["bodypart"]["poses"][0][0][0])

#         ## ADD POSE TO VIDEO
#         for keypoint in pose["bodypart"]["poses"][0][0][0]:  # Adjust this depending on the structure of `pose`
#                 x, y = int(keypoint[0]), int(keypoint[1])
#                 cv2.circle(frame, (x, y), 5, (0, 255, 0), -1)
        
#         # Write the frame with key points to the output video
#         out.write(frame)
    

#         frame_index += 1
#         print(frame_index)
    
#     # Release the video capture object
#     cap.release()
#     out.release()
    
#     return poses

In [40]:
from dlclive import DLCLive, Processor
import dlclive
from dlclive.display import Display
import cv2
import numpy as np 

In [43]:
import torch

dlc_proc = Processor()
dlc_live = DLCLive(pytorch_cfg="/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/train", processor=dlc_proc, snapshot='/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/train/snapshot-263.pt', model_type='pytorch') #change model type to 'pytorch' for raw .pt model

#very short video
#video_path = '/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/1_20cms_0degUP_first_03s.avi'
#short video
video_path = '/Users/annastuckert/Documents/DLC_AI_Residency/DLC_AI2024/DeepLabCut-live/Ventral_gait_model/1_20cms_0degUP_first_1s.avi'

poses = analyze_video2(video_path, dlc_live)

a
b
c
e
f
g
tensor([ 75.7766, 166.8159,   0.8967], grad_fn=<SelectBackward0>)
1
a
b
c
e
f
g
tensor([ 77.3931, 167.3282,   0.8872], grad_fn=<SelectBackward0>)
2
a
b
c
e
f
g
tensor([ 78.4710, 167.0059,   0.8916], grad_fn=<SelectBackward0>)
3
a
b
c
e
f
g
tensor([ 79.1370, 166.3917,   0.9038], grad_fn=<SelectBackward0>)
4
a
b
c
e
f
g
tensor([ 79.2794, 166.0293,   0.8990], grad_fn=<SelectBackward0>)
5
a
b
c
e
f
g
tensor([ 79.9914, 166.2171,   0.8672], grad_fn=<SelectBackward0>)
6
a
b
c
e
f
g
tensor([ 82.4419, 165.7413,   0.8876], grad_fn=<SelectBackward0>)
7
a
b
c
e
f
g
tensor([ 84.0175, 165.6790,   0.9262], grad_fn=<SelectBackward0>)
8
a
b
c
e
f
g
tensor([ 84.8978, 164.7049,   0.9411], grad_fn=<SelectBackward0>)
9
a
b
c
e
f
g
tensor([ 84.8933, 163.8721,   0.9366], grad_fn=<SelectBackward0>)
10
a
b
c
e
f
g
tensor([ 85.2302, 163.2644,   0.9057], grad_fn=<SelectBackward0>)
11
a
b
c
e
f
g
tensor([ 85.9384, 162.3564,   0.8691], grad_fn=<SelectBackward0>)
12
a
b
c
e
f
g
tensor([ 86.2886, 162.140

: 

In [42]:
print(poses)

[{'bodypart': {'poses': tensor([[[[ 75.7766, 166.8159,   0.8967],
          [ 70.5980, 160.5351,   0.9100],
          [ 75.1433, 154.0471,   0.8739],
          [173.0354, 137.4777,   0.7662],
          [140.4317, 189.6651,   0.8353],
          [315.0182, 112.5858,   0.8863],
          [305.2694, 198.2803,   0.6218],
          [219.8547, 133.7054,   0.7284],
          [218.6871, 167.7025,   0.7292],
          [214.1058, 195.0486,   0.8460],
          [352.9371, 157.7508,   0.8105]]]], grad_fn=<CopySlices>)}}, {'bodypart': {'poses': tensor([[[[ 77.3931, 167.3282,   0.8872],
          [ 72.1320, 160.7259,   0.8663],
          [ 77.2185, 154.4316,   0.9040],
          [175.1591, 136.1623,   0.8322],
          [142.3961, 189.0255,   0.8688],
          [308.4182, 111.9791,   0.7897],
          [311.0846, 197.3638,   0.6679],
          [221.8126, 134.8544,   0.7671],
          [221.4995, 167.8509,   0.7300],
          [216.2980, 195.5353,   0.7513],
          [354.5556, 156.2282,   0.8033]]]]